### ISSUE TITLE
Is there a way to purchase a development account on Twitter to run this?

### ISSUE THREAD

**Issue by LandonTClipp** [Jxck-S/plane-notify#91]
Since Elon banned ElonJet even though he claims to be a bastion of free speech, we need to multiply. He lied to us after claiming he wouldn't ban it:

https://twitter.com/elonmusk/status/1589414958508691456

Elon is a liar and must be punished :) How can we purchase access to the Twitter API? The official approval process probably isn't being staffed by anyone at the moment. If someone could point me to how I can purchase a bot account from a third party (who is reputable obviously) that would be great.

**Comment by ghost** [comment]
Since in the policy they state "real time updates", I think a 10-minute delay (for example) might be enough to ~~circumvent the rule~~ make it work legitimately.

Edit: Musk himself talks about this possibility https://www.nbcwashington.com/news/national-international/twitter-elon-musk-jet-2/3234086/

**Comment by makrsmark** [comment]
https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api

**Comment by tigercoding56** [comment]
you could also port it to another platform to make his life difficult

**Comment by Jxck-S** [comment]
Twitter API is easy to access and still free today, (1500 tweets a month). They make you "apply," but it gives your instant access.
